build: false

environment:
  matrix:
    - MINICONDA: C:\Miniconda-x64
      MINGW: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64
      MSYS: C:\msys64
      BASH: C:\msys64\usr\bin\bash
    - MINICONDA: C:\Miniconda36-x64
      MINGW: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64
      MSYS: C:\msys64
      BASH: C:\msys64\usr\bin\bash

cache:
  # cache chocolatey portable installations (invalidate with change in appveyor.yml)
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  # cache msys packages
  - C:\msys64\var\cache\pacman\pkg

init:
  - cmd: "ECHO %MINICONDA%"
  - cmd: "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - cmd: "set PATH=%MINGW%;%MINGW%\\bin;%PATH%"
  - cmd: "set PATH=C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64;%PATH%"
  - cmd: "set CC=gcc"

install:
  - cinst miktex
  - cmd: "%BASH% -lc \"pacman -S --noconfirm mingw-w64-x86_64-cmocka\""
  - cmd: conda install -y matplotlib numpy scipy setuptools six pytest cython
  - cmd: python do.py run-python
  - cmd: python do.py install-postprocessing

test_script:
  # run the experiment
  - cmd: cd code-experiments\build\python
  - cmd: python example_experiment.py bbob
  - cmd: python -m cocopp -o .\postproc .\exdata\random_search_on_bbob_budget0002xD
  - cmd: cd ..\..\..
  # run the tests
  - cmd: python do.py test-c
  - cmd: python do.py build-python
  - cmd: python do.py test-python
  - cmd: python do.py test-java
  - cmd: python do.py test-preprocessing
  - cmd: python do.py test-postprocessing
  # - cmd: python do.py test-postprocessing-all
